// <auto-generated />
using System;
using FlavorMap.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlavorMap.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260411151706_RemoveUserAndFavorite")]
    partial class RemoveUserAndFavorite
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("FlavorMap.Api.Models.Place", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CuisineType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CulturalNarratives")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CultureImage")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiningFormat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DiningMoodExperience")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FoodWeight")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MenuImage")
                        .HasColumnType("TEXT");

                    b.Property<string>("MenuSeasonality")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MoodImage")
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonalRating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Season")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SeasonSection")
                        .HasColumnType("TEXT");

                    b.Property<string>("SocialMedia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StickerImage")
                        .HasColumnType("TEXT");

                    b.Property<string>("Vibe")
                        .HasColumnType("TEXT");

                    b.Property<string>("WeightImage")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Places");
                });

            modelBuilder.Entity("FlavorMap.Api.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PlaceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Season")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlaceId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("FlavorMap.Api.Models.Review", b =>
                {
                    b.HasOne("FlavorMap.Api.Models.Place", "Place")
                        .WithMany()
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Place");
                });
#pragma warning restore 612, 618
        }
    }
}
